version: '3'

services:
  test-kitchen-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_ENDPOINT=${REDIS_ENDPOINT}

  test-kitchen-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_ENDPOINT=${REDIS_ENDPOINT}

  test-kitchen-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - REDIS_ENDPOINT=${REDIS_ENDPOINT}


  caddy:
    image: caddy/caddy:2.7.3-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

