# Stage 1 - Build the base
FROM node:18-alpine AS base
WORKDIR /app
COPY src ./src
COPY package*.json ./
COPY tsconfig*.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile


# Stage 2 - Build the app
FROM base AS build
WORKDIR /app
RUN yarn build


# Stage 3 - Production
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --only-production
COPY --from=build /app/build ./

CMD ["node", "main.js"]